document.documentElement.classList.add('js');
const header=document.querySelector('.site-header');const progress=document.querySelector('.scroll-progress span');const menuBtn=document.querySelector('.menu-btn');const panel=document.querySelector('.mobile-panel');const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function onScroll(){const y=window.scrollY;if(header)header.classList.toggle('scrolled',y>28);const h=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(h?Math.min(100,y/h*100):0)+'%';if(!reduce){const a=document.querySelector('.hero-a');const b=document.querySelector('.hero-b');const p=document.querySelector('.page-hero-bg img');if(a)a.style.transform=`scale(1.05) translateY(${Math.min(30,y*.035)}px)`;if(b)b.style.transform=`scale(1.06) translateY(${Math.min(18,y*.02)}px)`;if(p&&y<innerHeight)p.style.transform=`scale(1.04) translateY(${Math.min(28,y*.025)}px)`}}window.addEventListener('scroll',onScroll,{passive:true});onScroll();
function closeMenu(){if(!menuBtn||!panel)return;menuBtn.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');panel.classList.remove('open');panel.setAttribute('aria-hidden','true');document.body.classList.remove('menu-open')}menuBtn?.addEventListener('click',()=>{const open=!panel.classList.contains('open');menuBtn.classList.toggle('open',open);menuBtn.setAttribute('aria-expanded',String(open));panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('menu-open',open)});panel?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
const items=[...document.querySelectorAll('.reveal')];if('IntersectionObserver' in window&&!reduce){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');io.unobserve(e.target)}}),{threshold:.06,rootMargin:'0px 0px -5% 0px'});items.forEach(el=>io.observe(el))}else{items.forEach(el=>el.classList.add('in-view'))}
const sight=document.querySelector('.cursor-sight');if(sight&&matchMedia('(pointer:fine)').matches&&!reduce){let x=-60,y=-60,tx=-60,ty=-60;document.addEventListener('mousemove',e=>{tx=e.clientX;ty=e.clientY});document.querySelectorAll('a,button,summary').forEach(el=>{el.addEventListener('mouseenter',()=>sight.classList.add('hot'));el.addEventListener('mouseleave',()=>sight.classList.remove('hot'))});document.addEventListener('mousedown',()=>sight.style.transform='translate(-50%,-50%) scale(.78)');document.addEventListener('mouseup',()=>sight.style.transform='translate(-50%,-50%) scale(1)');(function loop(){x+=(tx-x)*.34;y+=(ty-y)*.34;sight.style.left=x+'px';sight.style.top=y+'px';requestAnimationFrame(loop)})()}
if(!reduce&&matchMedia('(pointer:fine)').matches){document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)*.10;const y=(e.clientY-r.top-r.height/2)*.10;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')})}

// Harden remote Instagram thumbnails. Meta may return a network success that browsers
// refuse to render cross-origin; any failed/zero-size image reveals the stable fallback.
function verifyRemoteMedia(){document.querySelectorAll('img.instagram-hotlink').forEach(img=>{const fail=()=>{img.classList.add('media-broken');img.parentElement?.classList.add('media-fallback')};img.addEventListener('error',fail,{once:true});if(img.complete&&img.naturalWidth===0)fail()})}
verifyRemoteMedia();window.addEventListener('load',verifyRemoteMedia,{once:true});
