
(()=>{const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const header=$('.site-header'),menu=$('.menu-toggle'),nav=$('.nav-links');let lastY=scrollY;
const closeMenu=()=>{if(menu&&nav){menu.classList.remove('open');nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}};
if(menu&&nav){menu.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);menu.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open))});$$('a',nav).forEach(a=>a.addEventListener('click',closeMenu));}
addEventListener('scroll',()=>{const y=scrollY;header?.classList.toggle('scrolled',y>10);const pct=Math.min(100,(y/(document.documentElement.scrollHeight-innerHeight))*100);document.documentElement.style.setProperty('--scroll',pct+'%');if(innerWidth<820&&header){if(y>lastY&&y>180&&!nav?.classList.contains('open'))header.style.transform='translateY(-100%)';else header.style.transform='';}lastY=y;},{passive:true});
const compare=$('[data-compare]');if(compare&&!matchMedia('(prefers-reduced-motion: reduce)').matches){let active=false,auto=true,t=0;const set=x=>{const r=compare.getBoundingClientRect(),p=Math.max(12,Math.min(88,(x-r.left)/r.width*100));compare.style.setProperty('--reveal',p+'%')};compare.addEventListener('pointerdown',e=>{active=true;auto=false;compare.setPointerCapture(e.pointerId);set(e.clientX)});compare.addEventListener('pointermove',e=>{if(active)set(e.clientX)});compare.addEventListener('pointerup',()=>active=false);const tick=()=>{if(auto){t+=.012;compare.style.setProperty('--reveal',(61+13*Math.sin(t))+'%')}requestAnimationFrame(tick)};tick();}
$$('[data-tilt]').forEach(el=>{if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateX(${(-y*2.4).toFixed(2)}deg) rotateY(${(x*2.4).toFixed(2)}deg) translateY(-3px)`});el.addEventListener('pointerleave',()=>el.style.transform='')}});
const lb=$('.lightbox');$$('[data-lightbox]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();if(lb){$('img',lb).src=a.href;lb.classList.add('open');document.body.style.overflow='hidden'}}));const closeLb=()=>{if(lb){lb.classList.remove('open');document.body.style.overflow=''}};$('.lightbox button')?.addEventListener('click',closeLb);lb?.addEventListener('click',e=>{if(e.target===lb)closeLb()});addEventListener('keydown',e=>{if(e.key==='Escape'){closeLb();closeMenu()}});
const form=$('[data-mail-form]');form?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),subject='Demande de projet paysager — '+(fd.get('nom')||''),body=[`Nom : ${fd.get('nom')||''}`,`Téléphone : ${fd.get('telephone')||''}`,`E-mail : ${fd.get('email')||''}`,`Ville : ${fd.get('ville')||''}`,`Projet : ${fd.get('projet')||''}`,'',fd.get('message')||''].join('\n');location.href=`mailto:contact@paysagiste-lartetlamatiere.fr?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
})();
