
document.documentElement.classList.add('js');
const header=document.querySelector('.site-header');const toggle=document.querySelector('.menu-toggle');const menu=document.querySelector('.mobile-menu');
if(toggle&&menu){toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));toggle.classList.toggle('open',!open);menu.classList.toggle('open',!open);menu.setAttribute('aria-hidden',String(open));document.body.style.overflow=!open?'hidden':''});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');toggle.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-hidden','true');document.body.style.overflow=''}))}
const current=document.body.dataset.page;document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===current)a.classList.add('active')});
let lastY=window.scrollY;let ticking=false;function onScroll(){const y=window.scrollY;if(header){header.classList.toggle('scrolled',y>30);if(innerWidth<=620&&y>120&&y>lastY+5)header.classList.add('mobile-hidden');else if(y<lastY-5||y<100)header.classList.remove('mobile-hidden')}lastY=y;const h=document.documentElement.scrollHeight-innerHeight;const p=h>0?Math.min(100,(y/h)*100):0;const bar=document.querySelector('.scroll-progress');if(bar)bar.style.width=p+'%';ticking=false}window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(onScroll);ticking=true}},{passive:true});onScroll();
document.querySelectorAll('[data-compare]').forEach(c=>{const r=c.querySelector('input');const mask=c.querySelector('.compare-mask');const handle=c.querySelector('.compare-handle');if(r){const u=()=>{mask.style.width=r.value+'%';handle.style.left=r.value+'%'};r.addEventListener('input',u);u()}});
const io='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('pending');e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08}):null;document.querySelectorAll('.reveal').forEach(el=>{if(io){el.classList.add('pending');io.observe(el)}});
document.querySelectorAll('.filter-bar button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-bar button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('.gallery-item').forEach(it=>it.classList.toggle('hidden',f!=='all'&&it.dataset.category!==f))}));
