document.documentElement.classList.add('js');
const menuBtn=document.querySelector('.menu-btn'), panel=document.querySelector('.mobile-panel');
if(menuBtn&&panel){menuBtn.addEventListener('click',()=>{const o=panel.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(o));});panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{panel.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));}
const obs=('IntersectionObserver'in window)?new IntersectionObserver((entries)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');obs.unobserve(e.target)}}),{threshold:.12}):null;
document.querySelectorAll('.reveal').forEach(el=>{if(obs)obs.observe(el);else el.classList.add('is-visible')});
document.querySelectorAll('.faq-item').forEach((item,i)=>{const q=item.querySelector('.faq-q');if(!q)return;q.addEventListener('click',()=>{const open=item.classList.toggle('open');q.setAttribute('aria-expanded',String(open));});});
const progress=document.querySelector('.scroll-progress');if(progress){const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?(scrollY/max*100):0)+'%'};addEventListener('scroll',update,{passive:true});update();}
const stage=document.querySelector('.hero-stage');if(stage&&!matchMedia('(prefers-reduced-motion: reduce)').matches){stage.addEventListener('pointermove',e=>{if(innerWidth<821)return;const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;stage.querySelectorAll('.hero-bottle').forEach((b,i)=>{const d=i===1?20:11;const base=b.classList.contains('left')?' rotate(-7deg)':b.classList.contains('right')?' rotate(8deg)':'';b.style.transform=`translate(${x*d}px,${y*d}px)${base}`})});stage.addEventListener('pointerleave',()=>stage.querySelectorAll('.hero-bottle').forEach(b=>b.style.transform=''));}
let lastY=0;const header=document.querySelector('.site-header');addEventListener('scroll',()=>{if(innerWidth<=820&&header){const y=scrollY;header.style.transform=(y>lastY&&y>120)?'translateY(-100%)':'translateY(0)';lastY=y}}, {passive:true});
