document.documentElement.classList.add('js');
const header=document.querySelector('.site-header');
const progress=document.querySelector('.scroll-progress span');
const menuBtn=document.querySelector('.menu-btn');
const mobilePanel=document.querySelector('.mobile-panel');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function updateScroll(){const y=scrollY;header?.classList.toggle('scrolled',y>24);const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(max?Math.min(100,y/max*100):0)+'%';const photo=document.querySelector('.hero-photo img');if(photo&&!reduced&&y<innerHeight)photo.style.transform=`scale(1.06) translate3d(0,${Math.min(25,y*.022)}px,0)`}
addEventListener('scroll',updateScroll,{passive:true});updateScroll();
function closeMenu(){menuBtn?.classList.remove('open');menuBtn?.setAttribute('aria-expanded','false');mobilePanel?.classList.remove('open');mobilePanel?.setAttribute('aria-hidden','true');document.body.style.overflow=''}
menuBtn?.addEventListener('click',()=>{const open=!mobilePanel.classList.contains('open');menuBtn.classList.toggle('open',open);menuBtn.setAttribute('aria-expanded',String(open));mobilePanel.classList.toggle('open',open);mobilePanel.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':''});
mobilePanel?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
if(!reduced&&'IntersectionObserver' in window){const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('play');io.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el))}
const sight=document.querySelector('.cursor-sight');if(sight&&matchMedia('(pointer:fine)').matches&&!reduced){let x=-50,y=-50,tx=-50,ty=-50;addEventListener('mousemove',e=>{tx=e.clientX;ty=e.clientY});document.querySelectorAll('a,button,summary,input,select,textarea').forEach(el=>{el.addEventListener('mouseenter',()=>sight.classList.add('hot'));el.addEventListener('mouseleave',()=>sight.classList.remove('hot'))});(function follow(){x+=(tx-x)*.28;y+=(ty-y)*.28;sight.style.left=x+'px';sight.style.top=y+'px';requestAnimationFrame(follow)})()}
if(!reduced&&matchMedia('(pointer:fine)').matches){document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.08}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')})}
const copyBtn=document.querySelector('#copy-request');copyBtn?.addEventListener('click',async()=>{const d=document.querySelector('#date')?.value||'[preferred date]';const g=document.querySelector('#guests')?.value||'[number of guests]';const f=document.querySelector('#format')?.value||'Not sure yet';const n=document.querySelector('#note')?.value?.trim();const text=`Hello Bangkok Shooting Experience, I would like to check availability.\nPreferred date: ${d}\nParticipants: ${g}\nFormat: ${f}${n?`\nNote: ${n}`:''}`;const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText(text);if(status)status.textContent='Booking request copied. Paste it into the Instagram DM.'}catch{if(status)status.textContent=text}});
